const p1 =
  "https://res.cloudinary.com/dr99oorie/image/upload/v1601449699/p3_okn4y4.png";
const p2 =
  "https://res.cloudinary.com/dr99oorie/image/upload/v1601449699/p1_swqc8p.png";
const p3 =
  "https://res.cloudinary.com/dr99oorie/image/upload/v1602127562/yJqeR0L4pr_t1yzpy.png";
const p4 =
  "https://res.cloudinary.com/dr99oorie/image/upload/v1602127496/JkOpmVM0vr_cixagr.png";

export const cardData = {
  tab1: {
    row1: {
      images: [p1, p1, p1, p1, p1, p1, p1, p1, p1, p1, p1, p1],
      prices: [123, 234, 345, 456, 567, 678, 123, 234, 345, 456, 567, 678],
      titles: [
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
      ],
      descriptions: [
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
      ],
      hrefs: [
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
      ],
      nums: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
    },
    row2: {
      images: [p1, p1, p1, p1, p1, p1],
      prices: [123, 234, 345, 456, 567, 678],
      titles: [
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
      ],
      descriptions: [
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
      ],
      hrefs: [
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
      ],
      nums: [5, 5, 5, 5, 5, 5],
    },
  },
  tab2: {
    row1: {
      images: [p2, p2, p2, p2, p2, p2, p2, p2, p2, p2, p2, p2],
      prices: [123, 234, 345, 456, 567, 678, 123, 234, 345, 456, 567, 678],
      titles: [
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
      ],
      descriptions: [
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
      ],
      hrefs: [
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
      ],
      nums: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
    },
    row2: {
      images: [p1, p1, p1, p1, p1, p1],
      prices: [123, 234, 345, 456, 567, 678],
      titles: [
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
      ],
      descriptions: [
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
      ],
      hrefs: [
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
      ],
      nums: [5, 5, 5, 5, 5, 5],
    },
  },
  tab3: {
    row1: {
      images: [p3, p3, p3, p3, p3, p3, p3, p3, p3, p3, p3, p3],
      prices: [123, 234, 345, 456, 567, 678, 123, 234, 345, 456, 567, 678],
      titles: [
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
      ],
      descriptions: [
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
      ],
      hrefs: [
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
      ],
      nums: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
    },
    row2: {
      images: [p3, p3, p3, p3, p3, p3],
      prices: [123, 234, 345, 456, 567, 678],
      titles: [
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
      ],
      descriptions: [
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
      ],
      hrefs: [
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
      ],
      nums: [5, 5, 5, 5, 5, 5],
    },
  },
  tab4: {
    row1: {
      images: [p4, p4, p4, p4, p4, p4, p4, p4, p4, p4, p4, p4],
      prices: [123, 234, 345, 456, 567, 678, 123, 234, 345, 456, 567, 678],
      titles: [
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
      ],
      descriptions: [
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
      ],
      hrefs: [
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
      ],
      nums: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
    },
    row2: {
      images: [p1, p1, p1, p1, p1, p1],
      prices: [123, 234, 345, 456, 567, 678],
      titles: [
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
      ],
      descriptions: [
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
        "Moving queen size bed",
      ],
      hrefs: [
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
        "/service",
      ],
      nums: [5, 5, 5, 5, 5, 5],
    },
  },
};
